In [ ]:
# (1) 첨부된 code에서 Q-Learning이 어떻게 적용되었는지 정리해보세요!
# (2) 코드에서 gamma 값을 0.5 또는 0.99로 바꾸어 실행해보고, gamma 값을 다르게 설정하면 Q-matrix가 어떻게 변하는지 비교하여 정리해보세요!

In [1]:
import numpy as np
import random
import matplotlib.pyplot as plt

gamma = 0.8

#For matrices reward and q_matrix columns are in order (U, D, L, R, N)

# here the states are 0, 1, 2, 3 for convenience
# 0 is the startinf state
# 1 is state to the right of 0
# 2 is the snake-pit state
# 3 is the treasure(goal state)

reward = np.array([[0, -10, 0, -1, -1],
         [0, 10, -1, 0, -1],
         [-1, 0, 0, 10, -1],
         [-1, 0, -10, 0, 10]])

q_matrix = np.zeros((4,5))

# -1 represent invalid transitions
transition_matrix = np.array([[-1, 2, -1, 1, 0],
                  [-1, 3, 0, -1, 1],
                  [0, -1, -1, 3, 2],
                  [1, -1, 2, -1, 3]])

# for valid actions
# encode up as 0, down as 1, left as 2, right as 3, no action as 4
# the rows are the states
valid_action = np.array([[1, 3, 4],
             [1, 2, 4],
             [0, 3, 4],
             [0, 2, 4]])

for i in range(10): # 10 episodes
    start_state = 0
    current_state = start_state
    while current_state != 3:
        action = random.choice(valid_action[current_state])
        next_state = transition_matrix[current_state][action]
        future_rewards =[]
        for action_nxt in valid_action[next_state]:
            future_rewards.append(q_matrix[next_state][action_nxt])
        q_state = reward[current_state][action] + gamma*max(future_rewards)
        q_matrix[current_state][action] = q_state
        print(q_matrix)
        print('Q-matrix is updated')
        current_state = next_state
        if current_state == 3:
            print('goal state reached')

print('final q-matrix : ')
print(q_matrix)


[[ 0.  0.  0. -1.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
Q-matrix is updated
[[ 0.  0.  0. -1.  0.]
 [ 0. 10.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
Q-matrix is updated
goal state reached
[[  0. -10.   0.  -1.   0.]
 [  0.  10.   0.   0.   0.]
 [  0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.]]
Q-matrix is updated
[[  0. -10.   0.  -1.   0.]
 [  0.  10.   0.   0.   0.]
 [  0.   0.   0.  10.   0.]
 [  0.   0.   0.   0.   0.]]
Q-matrix is updated
goal state reached
[[  0. -10.   0.  -1.  -1.]
 [  0.  10.   0.   0.   0.]
 [  0.   0.   0.  10.   0.]
 [  0.   0.   0.   0.   0.]]
Q-matrix is updated
[[  0. -10.   0.   7.  -1.]
 [  0.  10.   0.   0.   0.]
 [  0.   0.   0.  10.   0.]
 [  0.   0.   0.   0.   0.]]
Q-matrix is updated
[[  0. -10.   0.   7.  -1.]
 [  0.  10.   0.   0.   0.]
 [  0.   0.   0.  10.   0.]
 [  0.   0.   0.   0.   0.]]
Q-matrix is updated
goal state reached
[[ 0. -2.  0.  7. -1.]
 [ 0. 10.  0.  0.  0.]
 [ 0. 

In [3]:
import numpy as np
import random
import matplotlib.pyplot as plt

gamma = 0.99

#For matrices reward and q_matrix columns are in order (U, D, L, R, N)

# here the states are 0, 1, 2, 3 for convenience
# 0 is the startinf state
# 1 is state to the right of 0
# 2 is the snake-pit state
# 3 is the treasure(goal state)

reward = np.array([[0, -10, 0, -1, -1],
         [0, 10, -1, 0, -1],
         [-1, 0, 0, 10, -1],
         [-1, 0, -10, 0, 10]])

q_matrix = np.zeros((4,5))

# -1 represent invalid transitions
transition_matrix = np.array([[-1, 2, -1, 1, 0],
                  [-1, 3, 0, -1, 1],
                  [0, -1, -1, 3, 2],
                  [1, -1, 2, -1, 3]])

# for valid actions
# encode up as 0, down as 1, left as 2, right as 3, no action as 4
# the rows are the states
valid_action = np.array([[1, 3, 4],
             [1, 2, 4],
             [0, 3, 4],
             [0, 2, 4]])

for i in range(10): # 10 episodes
    start_state = 0
    current_state = start_state
    while current_state != 3:
        action = random.choice(valid_action[current_state])
        next_state = transition_matrix[current_state][action]
        future_rewards =[]
        for action_nxt in valid_action[next_state]:
            future_rewards.append(q_matrix[next_state][action_nxt])
        q_state = reward[current_state][action] + gamma*max(future_rewards)
        q_matrix[current_state][action] = q_state
        print(q_matrix)
        print('Q-matrix is updated')
        current_state = next_state
        if current_state == 3:
            print('goal state reached')

print('final q-matrix : ')
print(q_matrix)


[[  0. -10.   0.   0.   0.]
 [  0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.]]
Q-matrix is updated
[[  0. -10.   0.   0.   0.]
 [  0.   0.   0.   0.   0.]
 [  0.   0.   0.  10.   0.]
 [  0.   0.   0.   0.   0.]]
Q-matrix is updated
goal state reached
[[ 0.  -0.1  0.   0.   0. ]
 [ 0.   0.   0.   0.   0. ]
 [ 0.   0.   0.  10.   0. ]
 [ 0.   0.   0.   0.   0. ]]
Q-matrix is updated
[[ 0.  -0.1  0.   0.   0. ]
 [ 0.   0.   0.   0.   0. ]
 [ 0.   0.   0.  10.   0. ]
 [ 0.   0.   0.   0.   0. ]]
Q-matrix is updated
goal state reached
[[ 0.  -0.1  0.  -1.   0. ]
 [ 0.   0.   0.   0.   0. ]
 [ 0.   0.   0.  10.   0. ]
 [ 0.   0.   0.   0.   0. ]]
Q-matrix is updated
[[ 0.  -0.1  0.  -1.   0. ]
 [ 0.   0.   0.   0.  -1. ]
 [ 0.   0.   0.  10.   0. ]
 [ 0.   0.   0.   0.   0. ]]
Q-matrix is updated
[[ 0.  -0.1  0.  -1.   0. ]
 [ 0.   0.  -1.   0.  -1. ]
 [ 0.   0.   0.  10.   0. ]
 [ 0.   0.   0.   0.   0. ]]
Q-matrix is updated
[[ 0.  -0.1  0.  -1.  -1. ]
 [ 

In [ ]:
import numpy as np
import random
import matplotlib.pyplot as plt

gamma = 0.5

#For matrices reward and q_matrix columns are in order (U, D, L, R, N)

# here the states are 0, 1, 2, 3 for convenience
# 0 is the startinf state
# 1 is state to the right of 0
# 2 is the snake-pit state
# 3 is the treasure(goal state)

reward = np.array([[0, -10, 0, -1, -1],
         [0, 10, -1, 0, -1],
         [-1, 0, 0, 10, -1],
         [-1, 0, -10, 0, 10]])

q_matrix = np.zeros((4,5))

# -1 represent invalid transitions
transition_matrix = np.array([[-1, 2, -1, 1, 0],
                  [-1, 3, 0, -1, 1],
                  [0, -1, -1, 3, 2],
                  [1, -1, 2, -1, 3]])

# for valid actions
# encode up as 0, down as 1, left as 2, right as 3, no action as 4
# the rows are the states
valid_action = np.array([[1, 3, 4],
             [1, 2, 4],
             [0, 3, 4],
             [0, 2, 4]])

for i in range(10): # 10 episodes
    start_state = 0
    current_state = start_state
    while current_state != 3:
        action = random.choice(valid_action[current_state])
        next_state = transition_matrix[current_state][action]
        future_rewards =[]
        for action_nxt in valid_action[next_state]:
            future_rewards.append(q_matrix[next_state][action_nxt])
        q_state = reward[current_state][action] + gamma*max(future_rewards)
        q_matrix[current_state][action] = q_state
        print(q_matrix)
        print('Q-matrix is updated')
        current_state = next_state
        if current_state == 3:
            print('goal state reached')

print('final q-matrix : ')
print(q_matrix)


### (1)
상태에 따라서 어떤 액션을 취하면 최대 얼마의 reward를 얻을 수 있는지 분석하고, 이를 계속해서 학습시키면서 미래에 처음부터 가장 합리적인 선택을 할 수 있도록 q-matrix를 사용하기 위해 학습시키는 것이라고 이해했다.

### (2)
gamma가 작으면 작은 값들은 더 작아지고, 큰 값들은 더 커지는 방향으로 편향성이 커진다. 따라서 agent가 어떤 행동을 하거나 하지 않을 동기가 gamma가 커질 수록 더 커진다고 이해했다.